version: '3.8'

services:
  admin:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      API_URL: http://api
    depends_on:
      - api
      - db

  api:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chamaweb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
