services:
  admin:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      API_URL: http://gateway
    depends_on:
      - chamados
      - tickets
      - actions
      - stats
      - db

  dashboard:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    environment:
      API_URL: http://gateway
    depends_on:
      - chamados
      - tickets
      - actions
      - stats
      - db

  criar:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    environment:
      API_URL: http://gateway
    depends_on:
      - chamados
      - tickets
      - actions
      - stats
      - db

  login:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    environment:
      API_URL: http://gateway
    depends_on:
      - db

  chamados:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  tickets:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  actions:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  stats:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  gateway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - login
      - dashboard
      - criar
      - admin
      - chamados
      - tickets
      - actions
      - stats

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chamaweb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
